# Site Settings
name: ActuaGaming
title: ActuaGaming
description: Aquí te informaremos sobre lo último del mundo de los videojuegos.
tags:
  - gaming
  - videojuegos
  - noticias de videojuegos
  - PlayStation
  - Xbox
  - Nintendo
  - PC
  - noticias de PC
  - PS3
  - noticias de PS3
  - PS4
  - noticias de PS4
  - PS5
  - noticias de PS5
  - Xbox 360
  - noticias de Xbox 360
  - Xbox One
  - noticias de Xbox One
  - Xbox Series X
  - noticias de Xbox Series X
  - Fortnite
  - PUBG
  - Rockstar Games
  - EA
  - Ubisoft
  - Facebook Gaming
  - Twitch
  - YouTube Gaming
email: actuagamingla@gmx.com
disqus_username: actuagamingla
show_hero: true
menu:
  - title: Home
    url: /
  - title: Análisis
    url: https://actuagamingla.github.io/tags/#analisis
  - title: eSports
    url: https://actuagamingla.github.io/tags/#eSports
  - title: Lanzamientos
    url: https://actuagamingla.github.io/tags/#lanzamientos
  - title: Noticias
    url: https://actuagamingla.github.io/tags/#Noticias
  - title: 3DS
    url: https://actuagamingla.github.io/tags/#3DS
  - title: Android / iOS
    url: https://actuagamingla.github.io/tags/#móviles
  - title: Nintendo Switch
    url: https://actuagamingla.github.io/tags/#Nintendo%20Switch
  - title: Otros
    url: https://actuagamingla.github.io/tags/#otros
  - title: PS4
    url: https://actuagamingla.github.io/tags/#PS4
  - title: PS5
    url: https://actuagamingla.github.io/tags/#PS5
  - title: Retro
    url: https://actuagamingla.github.io/tags/#retro
  - title: Xbox One
    url: https://actuagamingla.github.io/tags/#Xbox%20One
  - title: Xbox Series X
    url: https://actuagamingla.github.io/tags/#Xbox%20Series%20X
  - title: Feed
    url: /feed.xml


# Social Media Settings
# Remove the item if you don't need it
github_username: actuagamingla
facebook_username: ActuaGamingLA
twitter_username: ActuaGamingLA
instagram_username: actuagamingla


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://actuagamingla.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "es"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.0
